services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty : true
    stdin_open : true
    command: bash ./gradlew bootrun
    ports: 
      - "4000:80"
    volumes:
      - ./schedule:/app
    working_dir: /app
